### ISSUE TITLE
Input? 

### ISSUE THREAD

**Issue by noncodo** [l-urence/smith-waterman#1]
Would you be abel to describe the usage a bit more? Like what the input files should look like?

**Comment by l-urence** [comment]
Sorry for answering this so late. But maybe someone else is stumbling about the same problem. 

This project was just a case study how to implement Smith Waterman with using OpenCL. We just used random generated strings to benchmark the implementation. I want also to point out that this implementation has some issues copying the matrixes to the GPU's memory. There might be a more performant implementation, so it actually speed up the computation using GPUs and not slowing it down.
